### ISSUE TITLE
Remove weighted average

### ISSUE THREAD

**Issue by comejv** [FBI-openup/Data-challenge-Sub-event-Detection-in-Twitter-streams#3]
Weighted average grouping drops event type column. Remove the function and replace with normal mean, as in original code.

**Comment by boyuan-zhangx** [comment]
Used time window to group but would lose the ID column . And can not find out why timewindow sorted by time stamp is 520 rows and ID is 516 rows. SO give up for now on using time window to group 
![image](https://github.com/user-attachments/assets/b52485f2-677c-4bd9-870a-4954920c2404)
